### ISSUE TITLE
Hey, is this plugin still OK for latest pug?

### ISSUE THREAD

**Issue by bushev** [bastidest/context-map-webpack-plugin#2]
Hi, thank you so much for this workaround!

I'm trying to bundle my AWS Lambda with PUG and getting the runtime error:

```
[~/IdeaProjects/***_backend]$ node run.local.js
TypeError: Cannot read property '1' of undefined
    at isFileType (fs.js:168:16)
    at Object.readFileSync (fs.js:345:16)
    at ***/dist/webpack:/node_modules/uglify-js/tools/node.js:28:1
    at Array.map (<anonymous>)
    at Object.<anonymous> (***/dist/webpack:/node_modules/uglify-js/tools/node.js:27:1)
    at __webpack_require__ (***/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (***/dost/webpack:/node_modules/pug-filters/lib/run-filter.js:4:14)
    at __webpack_require__ (***/dist/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (***/dist/webpack:/node_modules/pug-filters/index.js:3:21)
    at __webpack_require__ (***/dist/webpack:/webpack/bootstrap:19:1)
```

Do you have an idea, what's wrong here?

**Comment by bastidest** [comment]
Can you give more information on this? Is there a way to reproduce this issue with a minimal webpack config?
